name       : electrum
version    : 3.0.5
release    : 27
source     :
    - https://download.electrum.org/3.0.5/Electrum-3.0.5.tar.gz : 61ebc06782433f928853188762c6f3098bd3d08d54c34b5594233d196e51e01b
license    : MIT
component  : network.clients
summary    : Lightweight Bitcoin client
description: |
    Lightweight Bitcoin client
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - dnspython
    - python3-qt5
    - python-ecdsa
    - python-jsonrpclib
    - python-pbkdf2
    - python-protobuf
    - python-pyaes
    - python-pysocks
    - python-qrcode
    - python-six
    - python-slowaes
    - python-xmlrpclib
build      : |
    %python3_setup
install    : |
    %python3_install
    install -Dm00644 electrum.desktop $installdir/usr/share/applications/electrum.desktop
    install -Dm00644 icons/electrum.png $installdir/usr/share/pixmaps/electrum.png
    rm -rf $installdir/{home,root}
