name       : electrum
version    : 2.9.3
release    : 21
source     :
    - https://download.electrum.org/2.9.3/Electrum-2.9.3.tar.gz : c2192d4df6490fdc6e6f9f85b05db0e3915683a016a43ed444ebbc51ccfa0e34
license    : MIT
component  : network.clients
summary    : Lightweight Bitcoin client
description: |
    Lightweight Bitcoin client
builddeps  :
    - pkgconfig(python-2.7)
    - python-setuptools
rundeps    :
    - dnspython
    - python-ecdsa
    - python-jsonrpclib
    - python-pbkdf2
    - python-protobuf
    - python-pyaes
    - python-pysocks
    - python-qrcode
    - python-qt4
    - python-six
    - python-slowaes
build      : |
    %python_setup
install    : |
    %python_install
    install -Dm00644 $workdir/electrum.desktop $installdir/usr/share/applications/electrum.desktop
    install -Dm00644 $workdir/icons/electrum.png $installdir/usr/share/pixmaps/electrum.png
    rm -rf $installdir/{home,root}
