name       : electrum
version    : 2.7.10
release    : 6
source     :
    - https://download.electrum.org/2.7.10/Electrum-2.7.10.tar.gz : e538365252687e1e9f2f02d7a5de0af265348670f8f809ab8d19f92224878f6f
license    : MIT
component  : network.clients
summary    : Lightweight Bitcoin client
description: |
    Lightweight Bitcoin client
builddeps  :
    - pkgconfig(python-2.7)
    - python-setuptools
rundeps    :
    - python-ecdsa
    - python-jsonrpclib
    - python-pbkdf2
    - python-protobuf
    - python-qrcode
    - python-qt4
    - python-slowaes
build      : |
    %python_setup
install    : |
    %python_install
    install -Dm00644 $installdir/root/.local/share/applications/electrum.desktop \
        $installdir/usr/share/applications/electrum.desktop
    install -Dm00644 $installdir/root/.local/share/pixmaps/electrum.png \
        $installdir/usr/share/pixmaps/electrum.png
    rm -rf $installdir/root
