name       : electrum
version    : 3.1.2
release    : 32
source     :
    - https://download.electrum.org/3.1.2/Electrum-3.1.2.tar.gz : f5a67c616984e18646a6369e38d203e49e371ad904e6556ff445110f5ab44559
license    : MIT
component  : network.clients
summary    : Lightweight Bitcoin client
description: |
    Lightweight Bitcoin client
builddeps  :
    - pkgconfig(python3)
    - cython
rundeps    :
    - dnspython
    - python3-qt5
    - python-ecdsa
    - python-jsonrpclib
    - python-pbkdf2
    - python-protobuf
    - python-pyaes
    - python-pysocks
    - python-qrcode
    - python-six
    - python-slowaes
    - python-xmlrpclib
build      : |
    %python3_setup
install    : |
    %python3_install
    install -Dm00644 electrum.desktop $installdir/usr/share/applications/electrum.desktop
    install -Dm00644 icons/electrum.png $installdir/usr/share/pixmaps/electrum.png
    rm -rf $installdir/{home,root}
