name       : electrum
version    : 2.7.6
release    : 3
source     :
    - https://download.electrum.org/2.7.6/Electrum-2.7.6.tar.gz : bdb54d812a37839461589fe1fb908fa0590fe8bfaa50d0f6035dab58bafbc8a9
license    : MIT
component  : network.clients
summary    : Lightweight Bitcoin client
description: |
    Lightweight Bitcoin client
builddeps  :
    - pkgconfig(python-2.7)
    - python-setuptools
rundeps    :
    - python-ecdsa
    - python-jsonrpclib
    - python-pbkdf2
    - python-protobuf
    - python-qrcode
    - python-qt4
    - python-slowaes
build      : |
    %python_setup
install    : |
    %python_install
    install -Dm00644 $installdir/root/.local/share/applications/electrum.desktop \
        $installdir/usr/share/applications/electrum.desktop
    install -Dm00644 $installdir/root/.local/share/pixmaps/electrum.png \
        $installdir/usr/share/pixmaps/electrum.png
    rm -rf $installdir/root
