name       : electrum
version    : 3.3.1
release    : 35
source     :
    - https://download.electrum.org/3.3.1/Electrum-3.3.1.tar.gz : bdb7854f9b278bf1c59f46e1fd50d0ba5df0590c8e61d9642ee5d62dfa00451c
license    : MIT
component  : network.clients
summary    : Lightweight Bitcoin client
description: |
    Lightweight Bitcoin client
builddeps  :
    - pkgconfig(python3)
    - cython
rundeps    :
    - dnspython
    - python3-qt5
    - python-aiohttp_socks
    - python-aiorpcx
    - python-ecdsa
    - python-jsonrpclib
    - python-pbkdf2
    - python-protobuf
    - python-pyaes
    - python-pysocks
    - python-qrcode
    - python-six
    - python-slowaes
    - python-xmlrpclib
build      : |
    %python3_setup
install    : |
    %python3_install
    install -Dm00644 electrum.desktop $installdir/usr/share/applications/electrum.desktop
    install -Dm00644 icons/electrum.png $installdir/usr/share/pixmaps/electrum.png
    rm -rf $installdir/{home,root}
