name       : electrum
version    : 3.0.2
release    : 24
source     :
    - https://download.electrum.org/3.0.2/Electrum-3.0.2.tar.gz : 4dff75bc5f496f03ad7acbe33f7cec301955ef592b0276f2c518e94e47284f53
license    : MIT
component  : network.clients
summary    : Lightweight Bitcoin client
description: |
    Lightweight Bitcoin client
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - dnspython
    - python-ecdsa
    - python-jsonrpclib
    - python-pbkdf2
    - python-protobuf
    - python-pyaes
    - python-pysocks
    - python-qrcode
    - python3-qt5
    - python-six
    - python-slowaes
    - python-xmlrpclib
build      : |
    %python3_setup
install    : |
    %python3_install
    install -Dm00644 $workdir/electrum.desktop $installdir/usr/share/applications/electrum.desktop
    install -Dm00644 $workdir/icons/electrum.png $installdir/usr/share/pixmaps/electrum.png
    rm -rf $installdir/{home,root}
