name       : electrum
version    : 2.7.4
release    : 2
source     :
    - https://download.electrum.org/2.7.4/Electrum-2.7.4.tar.gz : 062ee3d85866813c8048f0b187c9fbe42faa042c91126d1282dffd3ecefa8635
license    : MIT
component  : network.clients
summary    : Lightweight Bitcoin client
description: |
    Lightweight Bitcoin client
builddeps  :
    - pkgconfig(python-2.7)
    - python-setuptools
rundeps    :
    - python-ecdsa
    - python-jsonrpclib
    - python-pbkdf2
    - python-protobuf
    - python-qrcode
    - python-qt4
    - python-slowaes
build      : |
    %python_setup
install    : |
    %python_install
    install -Dm00644 $installdir/root/.local/share/applications/electrum.desktop \
        $installdir/usr/share/applications/electrum.desktop
    install -Dm00644 $installdir/root/.local/share/pixmaps/electrum.png \
        $installdir/usr/share/pixmaps/electrum.png
    rm -rf $installdir/root
