name       : electrum
version    : 3.1.0
release    : 30
source     :
    - https://download.electrum.org/3.1.0/Electrum-3.1.0.tar.gz : e8f87fc2c36086e550c543e9fc0eac978c3bce85826c353c4f85248427f580c1
license    : MIT
component  : network.clients
summary    : Lightweight Bitcoin client
description: |
    Lightweight Bitcoin client
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - dnspython
    - python3-qt5
    - python-ecdsa
    - python-jsonrpclib
    - python-pbkdf2
    - python-protobuf
    - python-pyaes
    - python-pysocks
    - python-qrcode
    - python-six
    - python-slowaes
    - python-xmlrpclib
build      : |
    %python3_setup
install    : |
    %python3_install
    install -Dm00644 electrum.desktop $installdir/usr/share/applications/electrum.desktop
    install -Dm00644 icons/electrum.png $installdir/usr/share/pixmaps/electrum.png
    rm -rf $installdir/{home,root}
