name       : electrum
version    : 3.2.2
release    : 33
source     :
    - https://download.electrum.org/3.2.2/Electrum-3.2.2.tar.gz : 69cc3eaef8cc88e92730f3f38850a83e66ffd51d9aa26364f35fd45d1cedaabb
license    : MIT
component  : network.clients
summary    : Lightweight Bitcoin client
description: |
    Lightweight Bitcoin client
builddeps  :
    - pkgconfig(python3)
    - cython
rundeps    :
    - dnspython
    - python3-qt5
    - python-ecdsa
    - python-jsonrpclib
    - python-pbkdf2
    - python-protobuf
    - python-pyaes
    - python-pysocks
    - python-qrcode
    - python-six
    - python-slowaes
    - python-xmlrpclib
build      : |
    %python3_setup
install    : |
    %python3_install
    install -Dm00644 electrum.desktop $installdir/usr/share/applications/electrum.desktop
    install -Dm00644 icons/electrum.png $installdir/usr/share/pixmaps/electrum.png
    rm -rf $installdir/{home,root}
