name       : electrum
version    : 2.9.2
release    : 20
source     :
    - https://download.electrum.org/2.9.2/Electrum-2.9.2.tar.gz : 6a3f9bc8e205e696358d2cc7a98a39bc8f5d8b3d7a73bd178996c8264e7cf4dd
license    : MIT
component  : network.clients
summary    : Lightweight Bitcoin client
description: |
    Lightweight Bitcoin client
builddeps  :
    - pkgconfig(python-2.7)
    - python-setuptools
rundeps    :
    - dnspython
    - python-ecdsa
    - python-jsonrpclib
    - python-pbkdf2
    - python-protobuf
    - python-pyaes
    - python-pysocks
    - python-qrcode
    - python-qt4
    - python-six
    - python-slowaes
build      : |
    %python_setup
install    : |
    %python_install
    install -Dm00644 $workdir/electrum.desktop $installdir/usr/share/applications/electrum.desktop
    install -Dm00644 $workdir/icons/electrum.png $installdir/usr/share/pixmaps/electrum.png
    rm -rf $installdir/{home,root}
