name       : electrum
version    : 4.0.3
release    : 43
source     :
    - https://download.electrum.org/4.0.3/Electrum-4.0.3.tar.gz : 8f1a4d9e8623fcbd9e4ed9966c4744da51b6a148ddfacf5c97dfeffe9f0b0961
license    : MIT
component  : network.clients
summary    : Lightweight Bitcoin client
description: |
    Lightweight Bitcoin client
builddeps  :
    - pkgconfig(python3)
    - cython
rundeps    :
    - dnspython
    - python3-qt5
    - python-aiohttp_socks
    - python-aiorpcx
    - python-bitstring
    - python-cryptography
    - python-ecdsa
    - python-jsonrpclib
    - python-pbkdf2
    - python-protobuf
    - python-pyaes
    - python-pysocks
    - python-qrcode
    - python-six
    - python-slowaes
    - python-xmlrpclib
    - secp256k1
build      : |
    %python3_setup
install    : |
    %python3_install
    install -Dm00644 electrum.desktop $installdir/usr/share/applications/electrum.desktop
    install -Dm00644 electrum/gui/icons/electrum.png $installdir/usr/share/pixmaps/electrum.png
    rm -rf $installdir/{home,root}
