name       : electrum
version    : 2.8.2
release    : 16
source     :
    - https://download.electrum.org/2.8.2/Electrum-2.8.2.tar.gz : d8152bebc5c6f47b28a5d867707bc5742158fe544e7e8046d2c4747ae282b707
license    : MIT
component  : network.clients
summary    : Lightweight Bitcoin client
description: |
    Lightweight Bitcoin client
builddeps  :
    - pkgconfig(python-2.7)
    - python-setuptools
rundeps    :
    - dnspython
    - python-ecdsa
    - python-jsonrpclib
    - python-pbkdf2
    - python-protobuf
    - python-qrcode
    - python-qt4
    - python-six
    - python-slowaes
build      : |
    %python_setup
install    : |
    %python_install
    install -Dm00644 $workdir/electrum.desktop $installdir/usr/share/applications/electrum.desktop
    install -Dm00644 $workdir/icons/electrum.png $installdir/usr/share/pixmaps/electrum.png
    rm -rf $installdir/{home,root}
