name       : electrum
version    : 3.0.1
release    : 23
source     :
    - https://download.electrum.org/3.0.1/Electrum-3.0.1.tar.gz : 1aaabb1a89da659419c41ed68e55b0fe45c2afd69477117fd7833484751c0243
license    : MIT
component  : network.clients
summary    : Lightweight Bitcoin client
description: |
    Lightweight Bitcoin client
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - dnspython
    - python-ecdsa
    - python-jsonrpclib
    - python-pbkdf2
    - python-protobuf
    - python-pyaes
    - python-pysocks
    - python-qrcode
    - python3-qt5
    - python-six
    - python-slowaes
    - python-xmlrpclib
build      : |
    %python3_setup
install    : |
    %python3_install
    install -Dm00644 $workdir/electrum.desktop $installdir/usr/share/applications/electrum.desktop
    install -Dm00644 $workdir/icons/electrum.png $installdir/usr/share/pixmaps/electrum.png
    rm -rf $installdir/{home,root}
