name       : electrum
version    : '3.0'
release    : 22
source     :
    - https://download.electrum.org/3.0/Electrum-3.0.tar.gz : d1e9b81c10fd9c7ba214be4eaf84067a0b7d9b595945e938a8d67e86ddad8ca0
license    : MIT
component  : network.clients
summary    : Lightweight Bitcoin client
description: |
    Lightweight Bitcoin client
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - dnspython
    - python-ecdsa
    - python-jsonrpclib
    - python-pbkdf2
    - python-protobuf
    - python-pyaes
    - python-pysocks
    - python-qrcode
    - python3-qt5
    - python-six
    - python-slowaes
    - python-xmlrpclib
build      : |
    %python3_setup
install    : |
    %python3_install
    install -Dm00644 $workdir/electrum.desktop $installdir/usr/share/applications/electrum.desktop
    install -Dm00644 $workdir/icons/electrum.png $installdir/usr/share/pixmaps/electrum.png
    rm -rf $installdir/{home,root}
