name       : electrum
version    : 3.3.3
release    : 37
source     :
    - https://download.electrum.org/3.3.3/Electrum-3.3.3.tar.gz : c2692f1e1a21907a2b3e47564f06954a73d20017ca081238d07f65ae3c745f7c
license    : MIT
component  : network.clients
summary    : Lightweight Bitcoin client
description: |
    Lightweight Bitcoin client
builddeps  :
    - pkgconfig(python3)
    - cython
rundeps    :
    - dnspython
    - python3-qt5
    - python-aiohttp_socks
    - python-aiorpcx
    - python-ecdsa
    - python-jsonrpclib
    - python-pbkdf2
    - python-protobuf
    - python-pyaes
    - python-pysocks
    - python-qrcode
    - python-six
    - python-slowaes
    - python-xmlrpclib
build      : |
    %python3_setup
install    : |
    %python3_install
    install -Dm00644 electrum.desktop $installdir/usr/share/applications/electrum.desktop
    install -Dm00644 icons/electrum.png $installdir/usr/share/pixmaps/electrum.png
    rm -rf $installdir/{home,root}
